fast_gicp_client:
  ros__parameters:
    debug: true
    downsample_voxel_size: 0.05
    max_correspondence_distance: 0.5
    max_icp_iter: 50
    method: VGICP
    num_threads: 8
    x_bound: 10.0
    y_bound: 10.0
    z_bound: 5.0